### ISSUE TITLE
Make app secure by default

### ISSUE THREAD

**Issue by bencooper222** [VandyHacks/vaken#102]
From: https://www.troyhunt.com/the-6-step-happy-path-to-https/

Stuff we can do in this repository: 
- [ ] Set up a CSP (at a minimum upgrade-insecure requests)
- [ ] Set up CSP reporting

**Comment by leonm1** [comment]
We have Cloudflare handle HTTPS and we have HSTS enabled. Please reopen if this is not good enough, but I believe this to be sufficient.
