### ISSUE TITLE
Team model shouldn't keep track of size

### ISSUE THREAD

**Issue by cktang88** [VandyHacks/vaken#12]
Size should be aggregated whenever needed by getting length of array, not separate field. Separate field is easy to forget to update, etc.

**Comment by leonm1** [comment]
This can be easily implemented as a field in graphql that does not have a corresponding db field. It can then be achieved in the resolver by simply returning the length field of the team members array

**Comment by leonm1** [comment]
This appears to have been fixed at some point.
https://github.com/VandyHacks/vaken/blob/0ea905db0185885361bb8e7b24c83487fe92ee12/src/common/schema.graphql.ts#L206
