### ISSUE TITLE
Replace mstade/passport-google-oauth2

### ISSUE THREAD

**Issue by bencooper222** [VandyHacks/vaken#128]
This package isn't well maintained, not tested and generally subpar. We should either make PRs to fix these or find something else.

**Comment by cktang88** [comment]
We don't actually import that, we actually use https://www.npmjs.com/package/passport-google-oauth

**Comment by bencooper222** [comment]
... so we should remove this package then?

**Comment by cktang88** [comment]
I'm working on that

**Comment by bencooper222** [comment]
Fixed in #138
