### ISSUE TITLE
Unify Github/Google OAuth2 auth callback patterns

### ISSUE THREAD

**Issue by cktang88** [VandyHacks/vaken#14]
https://github.com/VandyHacks/vaken/blob/dev/src/server/auth.ts

The Github and Google OAuth2 related code is really similar, can be refactored into common funcs.

**Comment by bencooper222** [comment]
https://codeclimate.com/github/VandyHacks/vaken/src/server/auth.ts#issue_5ce5f38e57953b00010000c9
