### ISSUE TITLE
Support dark mode

### ISSUE THREAD

**Issue by bencooper222** [VandyHacks/vaken#153]
https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme

Already ready to go in Firefox and Safari and coming to Chromium later this summer!

**Comment by leonm1** [comment]
This shouldn't be _too_ difficult. Definitely look at the global style sheet in `src/client/app.tsx`, but I believe a theme may be required. The addition of storybook will make this significantly easier, as we can catch things more easily. In that case, add a dark mode story for every single story.

**Comment by siraben** [comment]
Fixed by #814.
