### ISSUE TITLE
Fix "method_complexity" issue in src/client/components/Buttons/RadioSlider.tsx

### ISSUE THREAD

**Issue by bencooper222** [VandyHacks/vaken#171]
Function `RadioSlider` has a Cognitive Complexity of 26 (exceeds 5 allowed). Consider refactoring.

https://codeclimate.com/github/VandyHacks/vaken/src/client/components/Buttons/RadioSlider.tsx#issue_5ce639c435e57100010000c2

**Comment by cktang88** [comment]
outdated
