### ISSUE TITLE
Fix "similar-code" issue in src/client/routes/dashboard/OrganizerDash.tsx

### ISSUE THREAD

**Issue by bencooper222** [VandyHacks/vaken#172]
Similar blocks of code found in 2 locations. Consider refactoring.

https://codeclimate.com/github/VandyHacks/vaken/src/client/routes/dashboard/OrganizerDash.tsx#issue_5ce639ca35e57100010000dd

**Comment by bencooper222** [comment]
Use Object.entries

**Comment by gfting** [comment]
So are the steps to pretty much just squash the things that codeclimate found

**Comment by cktang88** [comment]
Yeah pretty much

**Comment by cktang88** [comment]
outdated
