### ISSUE TITLE
Fix "identical-code" issue in src/client/routes/manage/HackerTable.tsx

### ISSUE THREAD

**Issue by bencooper222** [VandyHacks/vaken#173]
Identical blocks of code found in 2 locations. Consider refactoring.

https://codeclimate.com/github/VandyHacks/vaken/src/client/routes/manage/HackerTable.tsx#issue_5ce639ca35e57100010000ce

**Comment by bencooper222** [comment]
https://codeclimate.com/github/VandyHacks/vaken/src/client/contexts/TableContext.ts/source#issue-e0387a1a4ab65e53449a6182a51e0864

Yeah not great

**Comment by cktang88** [comment]
outdated
