### ISSUE TITLE
Cache eslint runs

### ISSUE THREAD

**Issue by cktang88** [VandyHacks/vaken#176]
https://eslint.org/docs/user-guide/command-line-interface#caching

**Comment by bencooper222** [comment]
Can't find an obvious way to get this done in CI. Probably some cache command would work. We're at 15 seconds to run though so I don't think it's a big deal

**Comment by cktang88** [comment]
It might be useful for local too

**Comment by cktang88** [comment]
Caching actually makes it a lot faster
