### ISSUE TITLE
Consider moving typings to separate directory

### ISSUE THREAD

**Issue by bencooper222** [VandyHacks/vaken#18]
As far as I can tell, this is mostly standard practice at any non-trivial size.

Example:  https://github.com/Microsoft/vscode/blob/master/src/typings/

**Comment by bencooper222** [comment]
In particular, make them common between server and client.

**Comment by bencooper222** [comment]
Looking into this, this isn't best practice for self-written code. It should only be used to document external code. We should still look into refactoring similar code to use common interfaces.

**Comment by cktang88** [comment]
#261 most likely makes this unnecessary
