### ISSUE TITLE
Allow console.log for frontend dev

### ISSUE THREAD

**Issue by bencooper222** [VandyHacks/vaken#180]
The current state of our logging is that we use pino on the backend and we use console.log on the frontend - even though it's against eslint rules. Instead of using console.log on the frontend and then deleting is prior to push (potentially losing out on valuable dev diagnostics), let's:

- [x] allow console.log ONLY for the client
- [ ] alter the prod webpack config to clean out console.logs at transpile time.

**Comment by cktang88** [comment]
#154 alters client eslint config to allow console

**Comment by cktang88** [comment]
Use https://github.com/webpack-contrib/terser-webpack-plugin to strip console.logs for prod
