### ISSUE TITLE
Lint config broken for server

### ISSUE THREAD

**Issue by bencooper222** [VandyHacks/vaken#198]
https://circleci.com/gh/VandyHacks/vaken/1105

Seems to be related to: https://github.com/benmosher/eslint-plugin-import/issues/1285

**Comment by cktang88** [comment]
Yeah #154 will close this

**Comment by bencooper222** [comment]
No, it's there too: https://circleci.com/gh/VandyHacks/vaken/996?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link

**Comment by bencooper222** [comment]
I think #114 does fix it but I'd have to rebase it to be sure
