### ISSUE TITLE
Serve img assets and such via S3 or something that's cached

### ISSUE THREAD

**Issue by bencooper222** [VandyHacks/vaken#20]
This wholly depends on how assets are served: it's not a big deal for us to serve assets via heroku if every mutation of them has a unique link (i.e. `name.png` is transformed to `name.sha1_hash.png`) that can be aggressively cached by Cloudflare but if we're not doing that, then we need to upload these to S3 to be served to users. 

Since CF is in front no matter what, it shouldn't matter to *us* what we do but, since this is meant to be generic, I'd probably suggest we build some sort of native S3 support it.

**Comment by cktang88** [comment]
I don't think any hackathon is at a scale for this to matter

**Comment by leonm1** [comment]
Webpack hashes the name of images imported through `file-loader`.
