### ISSUE TITLE
GoogleOAuth only works with @vanderbilt.edu emails

### ISSUE THREAD

**Issue by cktang88** [VandyHacks/vaken#221]
![image](https://user-images.githubusercontent.com/10319942/58372393-22056b80-7ee2-11e9-977f-eaadce8020d6.png)
@ftiet any ideas why? I'm using your env file

**Comment by ftiet** [comment]
When @AlanWilms set it up it allows only Vanderbilt emails, may need to change the setup

**Comment by cktang88** [comment]
Can you make a PR to the README that says this?

**Comment by ftiet** [comment]
We should just change it to allow any gmail account

**Comment by AlanWilms** [comment]
Am overseas right now and will be for a month, so am unable to handle this bug, sorry. Would recommend using someone else’s account as the admin for the Google OAuth settings in order to open it up to all emails

**Comment by bencooper222** [comment]
Is this fixed?

**Comment by cktang88** [comment]
don't think so, the issue is named badly, basically it still only allows vandy emails, and we want to support all google oauths

**Comment by ftiet** [comment]
I think it might be setup on Alan's personal google account so we should move to using a new one

**Comment by bencooper222** [comment]
@leonm1 / @geomaster453 should look into a proper Google organization account then.

**Comment by bencooper222** [comment]
@leonm1 resolve, right?

**Comment by leonm1** [comment]
Resolved
