### ISSUE TITLE
Add GitHub apps and integrations

### ISSUE THREAD

**Issue by bencooper222** [VandyHacks/vaken#26]
- [x] Something to run our linting - consider actual *writing* lint results
- [x] Code coverage integrating with istanbul
- [x] CircleCI
- [x] PR review system
- [x] Autobuild documentation site. 
- [x] Remove snyk because GH vulnerability alerts

**Comment by cktang88** [comment]
code coverage is gonna be useless until we after we write significant amounts of tests

**Comment by bencooper222** [comment]
I mean not *useless*, just not especially meaningful. No point in not setting it up alongside tests though.

**Comment by bencooper222** [comment]
Related: #35, #33

**Comment by bencooper222** [comment]
Related: #42
