### ISSUE TITLE
As an organizer, I can see a paginated list of hackers who have "organizer action needed"

### ISSUE THREAD

**Issue by leonm1** [VandyHacks/vaken#265]
# As an organizer, I can see a paginated list of hackers who have "organizer action needed"

## Implementation of organizer action

Given that the current function returns a promise that resolves to an array of Hackers, I'd like to begin by awaiting the Promise. This will give us an array of Hackers. We can access the "organizer action needed" property on each Hacker (don't know what the specific name is) and use the built in Array.filter() function to create an array of Hackers who satisfy this property.

## Implementation of paginated list

From what I've seen at work, material design already has a good paginated list that I think would be good to use. I think it's called mat-pag-table or something along those lines. Anyway, just use this paginated table to display the array by converting the array into whatever object the table needs (I think it's a DataSource object). This is going to be much more robust and easier than creating a paginated table from scratch, though that's obviously an option.

**Comment by timothycobrien** [comment]
## Aside

We could implement the filter on the paginated table itself of course, so that we could let organizers filter by any value of this parameter or by other parameters as well. I think the mat-page-table has this functionality, though if not, something else in material design definitely has that. Might not be this specific thing, but I've seen it in the same spot.

**Comment by cktang88** [comment]
Those are good thoughts, but why are we even having a paginated list? Can't we just use https://github.com/bvaughn/react-virtualized which we already use for the main table of hackers? @leonm1

**Comment by cktang88** [comment]
If we're just doing frontend filter, it's like a one-line change. Backend filters are actually possible too, and would probably be more work but also more efficient https://medium.com/open-graphql/implementing-search-in-graphql-11d5f71f179

**Comment by leonm1** [comment]
Hmm... Would y'all like to chat about this via meet and see if we can come to a conclusion?

**Comment by timothycobrien** [comment]
Yep, free all of today.
