### ISSUE TITLE
As an organizer, I can create a sponsor account by adding an email

### ISSUE THREAD

**Issue by leonm1** [VandyHacks/vaken#267]
From @xuezzou: 
- Sponsor to login
   - Give sponsor email and password
   - Let them modify password themselves and login into the corresponding dashboard
   - Tech
       - (Not in this issue) Sponsor dashboard - already has section: dashboard profile help - all need rewritten
- Organizer create sponsor account by providing email
   - Current
       - Manage Sponsors section: ‘not ready yet’ in NotReady.tsx
       - Tech - Add create sponsor first
           - click ‘Create’ Button + provide email
           - add authlevel sponsor to database w/ email and a default password
           - (not in this issue maybe) but also think about table like hackers to manage after adding

**Comment by cktang88** [comment]
Would the email need to be verified by sending the sponsor an email?

**Comment by leonm1** [comment]
Thank you for sending along your proposal @xuezzou! I have just a few thoughts: we don't want to use password login for anything anymore as it is very complex and hard to get right security wise. I think my recommendation is to extend the UI to allow for this type of flow:

1. company (with representative A with email A@company.org) becomes sponsor
2. vh sponsorship member asks for email they can use to sign in
3. representative asks for the following emails to be granted access: A@company.org and B@gmail.com 
4. sponsorship member adds A@company.org and B@gmail.com to whitelist
5. anyone who creates an account with A@company.org and B@gmail.com will have the permissions of that sponsor.

This would require you to add a collection to the database for storing unregistered sponsors' emails and checking for the presence of the email when a new user registers with the oauth. This functionality is in https://github.com/VandyHacks/vaken/blob/b733ea34bcaeea1be4396b520b6fd7dcd935c369/src/server/auth/helpers.ts#L30

**Comment by timothycobrien** [comment]
Is [this](https://auth0.com/docs/link-accounts) relevant? I think delegating most things to the OAuth API is good, because Auth is tricky/not secure/verbose to implement manually

**Comment by xuezzou** [comment]
Do we need a different interface for sponsors/organizer to login? since sponsor are not login thru either google or GitHub

**Comment by xuezzou** [comment]
@leonm1 To clarify the workflow:
sponsor would login thru the gmail they provided, and then we recognized the email as a sponsor and then login into the corresponding sponsor interface.

**Comment by leonm1** [comment]
Yes! That's absolutely correct.

**Comment by cktang88** [comment]
--> any supported OAuth with that those whitelisted emails would be able to login
