### ISSUE TITLE
As an organizer, there is a page where I can check people into events

### ISSUE THREAD

**Issue by leonm1** [VandyHacks/vaken#268]

**Comment by timothy-liang** [comment]
In the context of this issue specifically, is the page supposed to be finished appearance wise or just functional?

**Comment by leonm1** [comment]
Focus should be on function for now, but try to reuse components that already exist (i.e. don't write a new button component, as we have a few already that should work). It shouldn't be too hard to make everything fit in with the visual style that way.

**Comment by timothy-liang** [comment]
#399
