### ISSUE TITLE
Make an issue labeling system

### ISSUE THREAD

**Issue by bencooper222** [VandyHacks/vaken#29]
In particular, we badly need a no -> extreme priority classification system.

**Comment by cktang88** [comment]
how about:

**Priority tags**
[low-priority]
[medium-priority]
[high-priority]

**Type tags**
[wont-fix]
[bug]
[enhancement]
[question]

**Difficulty tags**
[good first issue]
[hard]

**Comment by cktang88** [comment]
i also like this https://medium.com/@dave_lunny/sane-github-labels-c5d2e6004b63

**Comment by bencooper222** [comment]
Should probably also add stuff regarding where the issue is - minimally "backend" & "frontend"
