### ISSUE TITLE
Webpack assets exceed recommended limit

### ISSUE THREAD

**Issue by bencooper222** [VandyHacks/vaken#301]
Either adjust this limit or do some lazy loading/code splitting:
<img width="1264" alt="image" src="https://user-images.githubusercontent.com/9143563/60834127-cb43b080-a174-11e9-9c15-0afae6731fc3.png">

**Comment by cktang88** [comment]
Lol we're not even close

**Comment by cktang88** [comment]
Code splitting by route is probably ideal
