### ISSUE TITLE
No email/password auth; only SSO

### ISSUE THREAD

**Issue by bencooper222** [VandyHacks/vaken#31]
From: https://vandyhacks.slack.com/archives/CDJEP2U1X/p1547665924001700?thread_ts=1547665121.000400&cid=CDJEP2U1X

>I'm very against traditional email/password auth. We're an amateur team that doesn't maintain this year round nor do we have a lot of security expertise. I don't think we should ask people to trust us with their passwords (particularly given password reuse: a way I like to think of it is that people are giving us their bank passwords).

We can keep it for testing if we really need it.

**Comment by leonm1** [comment]
Hiding it behind a testing flag would probably make things easier. It is quite convenient

**Comment by bencooper222** [comment]
🎉
