### ISSUE TITLE
Inputs don't work on Hacker /application page

### ISSUE THREAD

**Issue by cktang88** [VandyHacks/vaken#330]
On any hackerform input, typing doesn't do anything. (firefox)
Console:
```Warning: Failed prop type: You provided a `value` prop to a form field without an `onChange` handler. This will render a read-only field. If the field should be mutable use `defaultValue`. Otherwise, set either `onChange` or `readOnly`.
    in input (created by Context.Consumer)
    in StyledComponent (created by Calendar__StyledCalInput)
    in Calendar__StyledCalInput (created by CalendarInput)
    in CalendarInput (created by Application)
    in label (created by Context.Consumer)
    in StyledComponent (created by Application__StyledQuestion)
    in Application__StyledQuestion (created by Application)
    in div (created by Context.Consumer)
    in StyledComponent (created by Collapsible__CollapsibleBody)
    in Collapsible__CollapsibleBody (created by Collapsible)
    in div (created by Context.Consumer)
    in StyledComponent (created by Collapsible__BGDiv)
    in Collapsible__BGDiv (created by Collapsible)
    in Collapsible (created by Application)
    in form (created by Context.Consumer)
    in StyledComponent (created by Application__StyledForm)
    in Application__StyledForm (created by Application)
    in Application (created by Context.Consumer)
    in Route (created by Frame)
    in Switch (created by Frame)
    in Suspense (created by Frame)
    in div (created by Context.Consumer)
    in StyledComponent (created by FlexContainers__OverflowContainer)
    in FlexContainers__OverflowContainer (created by Frame)
    in div (created by Context.Consumer)
    in StyledComponent (created by Frame__Layout)
    in Frame__Layout (created by Frame)
    in Frame (created by StateMachine)
    in StateMachine (created by Vaken)
    in Router (created by BrowserRouter)
    in BrowserRouter (created by Vaken)
    in Vaken
    in ApolloProvider
    in ApolloProvider```

**Comment by cktang88** [comment]
I think this is broken from the Props changes in https://github.com/VandyHacks/vaken/commit/29a2b818c35d06f159aceb390ad1dda32fc20887#diff-42b53b803435031f7529fd3ff0eb6b9d ? @leonm1

**Comment by leonm1** [comment]
Likely. Highly recommend using the new props/schema as the old is very complex. The new schema just uses strings as values for everything

**Comment by leonm1** [comment]
Fixed in #339
