### ISSUE TITLE
Firefox SVG compatibility issues

### ISSUE THREAD

**Issue by IrfaanKhalid** [VandyHacks/vaken#39]
<a href="https://github.com/AlanWilms"><img src="https://avatars0.githubusercontent.com/u/19272026?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [AlanWilms](https://github.com/AlanWilms)**
_Friday Mar 15, 2019 at 05:39 GMT_
_Originally opened as https://github.com/vu-cs3892-s19/vaken/issues/53_

----

Weird SVG behavior with Checkmark component and plane.svg

**Comment by IrfaanKhalid** [comment]
<a href="https://github.com/AlanWilms"><img src="https://avatars0.githubusercontent.com/u/19272026?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [AlanWilms](https://github.com/AlanWilms)**
_Friday Mar 15, 2019 at 05:41 GMT_

----

<img width="746" alt="Screen Shot 2019-03-15 at 12 41 31 AM" src="https://user-images.githubusercontent.com/19272026/54410834-195f1080-46bb-11e9-85f3-06a0d5a7a49c.png">

**Comment by IrfaanKhalid** [comment]
<a href="https://github.com/AlanWilms"><img src="https://avatars0.githubusercontent.com/u/19272026?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [AlanWilms](https://github.com/AlanWilms)**
_Wednesday Mar 27, 2019 at 17:36 GMT_

----

<img width="429" alt="Screen Shot 2019-03-27 at 12 35 15 PM" src="https://user-images.githubusercontent.com/19272026/55098967-e179a500-508c-11e9-95b5-3dacbf63e5e0.png">
Bug is less noticable
Running on Firefox Quantum 66.0.1 (64-bit)

**Comment by IrfaanKhalid** [comment]
<a href="https://github.com/leonm1"><img src="https://avatars3.githubusercontent.com/u/32306579?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [leonm1](https://github.com/leonm1)**
_Wednesday Mar 27, 2019 at 17:37 GMT_

----

- [ ] Make buttons the correct size

**Comment by IrfaanKhalid** [comment]
<a href="https://github.com/AlanWilms"><img src="https://avatars0.githubusercontent.com/u/19272026?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [AlanWilms](https://github.com/AlanWilms)**
_Thursday Apr 18, 2019 at 22:21 GMT_

----

Might need to change use of rem. . . 
See: https://bugzilla.mozilla.org/show_bug.cgi?format=default&id=1231147

**Comment by cktang88** [comment]
@leonm1 does the inline fix in #261 resolve this?

**Comment by cktang88** [comment]
doesn't seem to be a problem anymore
