### ISSUE TITLE
Profile Page

### ISSUE THREAD

**Issue by IrfaanKhalid** [VandyHacks/vaken#41]
<a href="https://github.com/AlanWilms"><img src="https://avatars0.githubusercontent.com/u/19272026?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [AlanWilms](https://github.com/AlanWilms)**
_Wednesday Mar 27, 2019 at 17:30 GMT_
_Originally opened as https://github.com/vu-cs3892-s19/vaken/issues/74_

----

- [x] Populate view with data from DB
- [ ] Submit new inputs back to DB

**Comment by cktang88** [comment]
@leonm1 are there any updates to this from #261 ?

**Comment by leonm1** [comment]
Yes, the second checkbox is accomplished with the current state of 261
