### ISSUE TITLE
Set up CI

### ISSUE THREAD

**Issue by IrfaanKhalid** [VandyHacks/vaken#42]
<a href="https://github.com/leonm1"><img src="https://avatars3.githubusercontent.com/u/32306579?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [leonm1](https://github.com/leonm1)**
_Wednesday Mar 27, 2019 at 17:47 GMT_
_Originally opened as https://github.com/vu-cs3892-s19/vaken/issues/77_

----

- [x] Linting should fail CI
- [x] Failed build should fail CI

**Comment by bencooper222** [comment]
[ ] Fail when npm audit fails

**Comment by cktang88** [comment]
Can we close this and just use #26 ?

**Comment by bencooper222** [comment]
Not doing `npm audit` because GitHub security alerts will catch that for us. Might integrate audit checks into github actions later but not worth doing in CI IMO.

**Comment by bencooper222** [comment]
I changed my mind on the audit thing. I think I'll have it fail CI if there's a *critical* vulnerability. To date, I have *never* seen one of these in a project of mine which says a lot about its frequency and severity should one appear. Will add to PR once this fucking stats final is over.
