### ISSUE TITLE
Get multiple schools for top N if they have same # of applicants

### ISSUE THREAD

**Issue by IrfaanKhalid** [VandyHacks/vaken#44]
<a href="https://github.com/ftiet"><img src="https://avatars1.githubusercontent.com/u/18177390?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [ftiet](https://github.com/ftiet)**
_Monday Apr 15, 2019 at 17:22 GMT_
_Originally opened as https://github.com/vu-cs3892-s19/vaken/issues/114_

----

In https://github.com/VandyHacks/vaken/blob/cce53e4cfe07cddfb88371fb2b5772855446718f/src/server/resolvers/HackerResolver.ts#L142 if other schools have the same # of applicants as the last school returned, return those also

**Comment by IrfaanKhalid** [comment]
<a href="https://github.com/AlanWilms"><img src="https://avatars0.githubusercontent.com/u/19272026?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [AlanWilms](https://github.com/AlanWilms)**
_Thursday Apr 18, 2019 at 00:17 GMT_

----

Can make this feature an option to either hard cap at the N or do N + any ties - possibly by passing a boolean

**Comment by bencooper222** [comment]
Not sure if there's any world where someone would want to not have ties. I don't think customization is the move here.

**Comment by ftiet** [comment]
So do we just want to always display ties? I think I have some code that fixes this from a while ago

**Comment by bencooper222** [comment]
There's no fair tiebreaker so it just becomes a random thing which is probably bad. I think always display ties is the move.

**Comment by leonm1** [comment]
This is no longer relevant as we never had a working hacker stats board.
