### ISSUE TITLE
`any` type in index expression in `/Input/Boolean.tsx`

### ISSUE THREAD

**Issue by cktang88** [VandyHacks/vaken#49]
![image](https://user-images.githubusercontent.com/10319942/56602236-9d61bd80-65c2-11e9-9691-613980ba3ff7.png)

**Comment by cktang88** [comment]
I can't even run `npm build` with this

**Comment by leonm1** [comment]
This is part of the issue behind the application components. If we were to use some sort of form library we could rid ourselves of these components. You can set the type of the index operator, but we'd need to standardize internal representation of data to strings or something -- honestly not a terrible idea

**Comment by cktang88** [comment]
Fixed temporarily by #178

**Comment by cktang88** [comment]
Keeping this open until we get a permanent type fix
