### ISSUE TITLE
dev-server script not cross-platform

### ISSUE THREAD

**Issue by cktang88** [VandyHacks/vaken#51]
Currently on windows:
![image](https://user-images.githubusercontent.com/10319942/56602524-4b6d6780-65c3-11e9-8d93-c6da02f5ef0b.png)

Replace with `"dev-server": "nodemon"` ?

**Comment by bencooper222** [comment]
(you're the only experienced dev who uses native windows terminal, I think)

**Comment by cktang88** [comment]
i feel personally attacked
