### ISSUE TITLE
Split HackerTable into separate components

### ISSUE THREAD

**Issue by cktang88** [VandyHacks/vaken#55]
https://github.com/VandyHacks/vaken/blob/dev/src/client/routes/manage/HackerTable.tsx

The nesting in particular is very troublesome:
![image](https://user-images.githubusercontent.com/10319942/58359339-a1def780-7e48-11e9-968b-a92a5853f60a.png)

Go for file size < 250 lines would be nice.

**Comment by bencooper222** [comment]
Also see #173

**Comment by bencooper222** [comment]
- [ ] create jest snapshot test BEFORE refactoring to compare before/after

**Comment by cktang88** [comment]
It's literally impossible to create a snapshot because it's too large and complex so it would require ridiculous mocking @bencooper222

**Comment by cktang88** [comment]
https://github.com/VandyHacks/vaken/commit/fb79a14730d0351349befb7c193bcccbec37c76a is the best I can do

**Comment by bencooper222** [comment]
Better than nothing, I guess? So long as we have a basis of what the eventual refactoring should look like

**Comment by cktang88** [comment]
Well that snap basically mocks the entire table as a blank...

**Comment by cktang88** [comment]
will close until this becomes a blocker on progress
