### ISSUE TITLE
Update deps

### ISSUE THREAD

**Issue by cktang88** [VandyHacks/vaken#57]
`npm outdated`
NOTE: we should also try to update as many major versions as we can, as long as it doesn't require significant code changes.

In the future hopefully we can automate this.

**Comment by bencooper222** [comment]
basically, we just need to figure out how #105 affects us. Unless there's a security or feature we need, I don't really think it's worth it for major versions until we have a full testing suite in place.

**Comment by bencooper222** [comment]
<img width="362" alt="image" src="https://user-images.githubusercontent.com/9143563/57975517-4b247a00-797f-11e9-8f49-7bfeced7688a.png">


Currently, these are the dependencies that we're behind on but are maximally updated according to our package.json spec

**Comment by bencooper222** [comment]
We have a bot constantly reminding us of this. I don't think we really need this issue anymore.
