### ISSUE TITLE
Button Styling in Admin Part 

### ISSUE THREAD

**Issue by saydus** [VandyHacks/vaken#637]
<img width="531" alt="Screen Shot 2020-06-28 at 7 58 14 PM" src="https://user-images.githubusercontent.com/29519144/85963092-b78eec80-b979-11ea-8824-673fed289fa4.png">
A small styling issue with the button in Manage Hackers section. White color for button text would look better.

**Comment by gfting** [comment]
Thanks–we forgot to do this.

**Comment by gfting** [comment]
This is pretty troll, somewhere the props are getting lost but it's working in the OAuth buttons with the same pattern. I'm blocked by a GraphQL error from debugging this further for a bit.
