### ISSUE TITLE
Switch to PostgreSQL

### ISSUE THREAD

**Issue by leonm1** [VandyHacks/vaken#64]
Mongo requires duplication of data. A relational database would be better

**Comment by cktang88** [comment]
wdym by duplication?

**Comment by leonm1** [comment]
https://www.postgresql.org/

**Comment by leonm1** [comment]
Our data is by nature relational; however, we currently aren't able to model that in mongo. Instead, we have different tables for `hacker` and `user`. The `hacker` database needs to duplicate all of the fields in `user` so that we can access them in a single struct -- all users have a `firstName`, and it is idiomatic for accessing those fields to be `queriedUser.firstName`, instead of `queriedUser.user.firstName`. Because we use these class models where hacker extends user, it makes little sense to have to duplicate all of the fields in both tables where a relational database would allow us to keep them in separate tables while representing them as one structure.

**Comment by bencooper222** [comment]
Our data is the posterchild for the relational use case.

**Comment by cktang88** [comment]
Okay but Mongo has:

- Atlas
- human readable dumps
- good interop with JS lang, allowing storing of whole JS objects, etc.

**Comment by leonm1** [comment]
* pgadmin4
* You got me on human readable dumps
* https://www.postgresql.org/docs/9.4/datatype-json.html

**Comment by bencooper222** [comment]
Regardless of whether or not this is the right choice, I don't think we're at the point where this really matters. Therefore, it's not worth the re-engineering effort IMO.

**Comment by cktang88** [comment]
The duplication of data is a large problem if we have to keep changing things in multiple places. If we do, then I'd seriously consider SQL. Otherwise, I think we're fine with Mongo because the majority of the app is already written and it's unlikely to undergo major modifications to the models in the future.

**Comment by cktang88** [comment]
If in the future we do switch, https://github.com/graphile/postgraphile might be useful

**Comment by bencooper222** [comment]
I'm closing this. If someone feels super strongly about this, feel free to reopen but I think two things are pretty true:

1. PSQL is the right move.
2. PSQL is not worth rewriting our code for our use case.
