### ISSUE TITLE
Add reminder about upcoming US Election

### ISSUE THREAD

**Issue by siraben** [VandyHacks/vaken#675]
Example: HackMIT puts a notice at the bottom of the confirmation screen, above the submit button. The text reads

## Box Title
> Reminder: Register to vote!

## Box Text

> If you are a US citizen, don't forget to register to vote – elections are in progress/coming up, so go make your voice heard!

Maybe we should add one in Vaken as well, I'm OK with putting it anywhere.

**Comment by aadibajpai** [comment]
this is moot now ig?
