### ISSUE TITLE
Add check-in for events during the hackathon

### ISSUE THREAD

**Issue by saydus** [VandyHacks/vaken#677]
We need to track event attendance of users during the hackathon. Since we will give out swag to those who attend events, we would need a way to know how many events people attend, and what the addresses of those who attend many events.

One way we were thinking is adding a check-in button on Vaken main page (it will check in for different events depending on times of the event) or seperate pages with unique URL's which we will send out during the event, and clicking the button will add an event to eventsAttended field for a user. 

If we have eventsAttended field populated after the hackathon, we will fetch top event attenders and send them swag to the address indicated during the registration process.

**Comment by gfting** [comment]
Some implementation details:
- You can reuse most of the logic that the Organizer has in the events pane. You can reuse the logic that pulls from Google Calendar to get the current event.
- You should create a new component that handles the UI for the user. Then, go to routes, as well as change the sidebar to allow hackers with auth to push check ins, just using their `me` object. I haven't fully thought about the security in this approach.

- In relation to the points system, you can grab some metadata from the event itself–look at the Google Calendar API for this information.

**Comment by aadibajpai** [comment]
closed in #696
