### ISSUE TITLE
Clean up eslint warnings and errors

### ISSUE THREAD

**Issue by bencooper222** [VandyHacks/vaken#71]
Pushing this to one task because needs to be done before we aggressively enforce CI and because it's a good first issue. 

There's a lot of warnings in the code that should be simple to clean up. In particular, I'm thinking of these rule violations:

- no-console
- no-shadow
- no-unused-vars (and @typescript-eslint/no-unused-vars)
- no-nested-ternary
- no-undef (!)

We can't start enforcing CI till this is fixed in the default branch because otherwise *every* PR will fail. Alternatively, we can change which rules we want to enforce in the config.

**Comment by cktang88** [comment]
no-console would break every single file in the repo

**Comment by cktang88** [comment]
no-unused-vars is good

is there something like no-unused-imports too

**Comment by cktang88** [comment]
Shouldn't we do this before we merge #76

**Comment by bencooper222** [comment]
Probably

**Comment by bencooper222** [comment]
our eslint errors have changed quite a bit since this issue.
