### ISSUE TITLE
Set OG Image for repo

### ISSUE THREAD

**Issue by bencooper222** [VandyHacks/vaken#72]
IMO Vaken (or whatever we rename it) deserves its own unique branding that should be a clever twist on the VandyHacks logo. Once we get that going, we should set the open graph image for the repo: https://github.blog/2019-04-17-custom-open-graph-images-for-repositories/

**Comment by cktang88** [comment]
I like the vaken logo Alan made

**Comment by bencooper222** [comment]
Asking in #design

**Comment by aadibajpai** [comment]
> Asking in #design

@bencooper222 do you remember if something was made or if there's an asset we can use?

**Comment by bencooper222** [comment]
Don’t think so but you can try searching #design for this feb and see if anything is there,

**Comment by aadibajpai** [comment]
I did that before, nothing there sadly

**Comment by leonm1** [comment]
I added this logo:
![vaken](https://user-images.githubusercontent.com/32306579/103462738-56afea80-4cf5-11eb-8503-a535abb94ac6.png)
