### ISSUE TITLE
Fix code that doesn't adhere to .editorconfig

### ISSUE THREAD

**Issue by bencooper222** [VandyHacks/vaken#75]
I used this on the merge that introduced the editorconfig to fix a bunch of files. Should we just have this be part of our lint process? https://github.com/jedmao/eclint

**Comment by cktang88** [comment]
how slow is it?

**Comment by bencooper222** [comment]
I don't recall from last night but it felt pretty fast. `npx eclint fix ./**/*` if you want to try.

**Comment by bencooper222** [comment]
Just ran it on dev and it made no changes. Let's consider this done.
