### ISSUE TITLE
Set minimum code coverage in Jest

### ISSUE THREAD

**Issue by bencooper222** [VandyHacks/vaken#79]
My guess is we'll end up setting this to be around 85%. Let's wait until we have more tests built out though - we don't want to build the habit of ignoring code coverage.
![0% Code coverage is great](https://shared.benc.io/screencaps/2019/04/7d0758c6-a6dd-40a2-a813-42949e942a48.png)

**Comment by cktang88** [comment]
lmfao

**Comment by bencooper222** [comment]
It's set in codecov.
