### ISSUE TITLE
Do something with contributors

### ISSUE THREAD

**Issue by bencooper222** [VandyHacks/vaken#801]
https://github.com/VandyHacks/vaken/blob/886253c228c4bce4105e67e0c4511abb8d13792b/package.json#L22-L29

I like seeing my name as much as the next guy but we should either a) make this exhaustive off all contributors or b) delete it and replace it with just general credits to VH with the info@ email. I prefer b).

**Comment by leonm1** [comment]
GitHub already keeps track of an exhaustive list of contributors via the contribution insights graph, so maybe just delete?
