### ISSUE TITLE
Webpack entry code error on `npm start`

### ISSUE THREAD

**Issue by cktang88** [VandyHacks/vaken#94]
![image](https://user-images.githubusercontent.com/10319942/57809858-140a5a80-772c-11e9-8e43-d316e04ceae9.png)
Windows 10

**Comment by bencooper222** [comment]
Looks like the fix is to turn the entry into an array: https://github.com/smooth-code/error-overlay-webpack-plugin/issues/37#issuecomment-485314212 (there's an amusing flame war on that issue).

Or someone could drop a PR to fix that repo.
